version: "3"

tasks:
  generate:end:
    cmds:
      - go run -mod=mod entgo.io/ent/cmd/ent generate ./ent/schema
  generate:graphql:
    cmds:
      - go run -mod=mod github.com/99designs/gqlgen generate
