// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/kokiebisu/mycontent/packages/service-blog/ent/blog"
)

type User struct {
	ID       string        `json:"id"`
	Interest blog.Interest `json:"interest"`
}
