services:
  registry:
    container_name: registry
    image: registry:2
    ports:
      - "5001:5000"

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - mycontent-network
    ports:
      - "5433:5432"

  service-authentication:
    container_name: service-authentication
    build:
      context: .
      dockerfile: ./packages/service-authentication/Dockerfile.dev
    networks:
      - mycontent-network
    environment:
      GRAPHQL_PORT: "4001"
      USER_GRPC_PORT: "50053"
      USER_SERVICE_HOST: "service-user"
    depends_on:
      service-user:
        condition: service_healthy
      service-blog:
        condition: service_healthy
    ports:
      - "4001:4001"
    volumes:
      - ./packages/service-authentication:/app/packages/service-authentication
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/playground"]
      interval: 5s
      timeout: 3s
      retries: 5

  service-blog:
    container_name: service-blog
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./packages/service-blog/Dockerfile.dev
    networks:
      - mycontent-network
    environment:
      GRAPHQL_PORT: "4002"
      BLOG_GRPC_PORT: "50052"
      S3_ENDPOINT: "http://localhost:4566"
      DB_PORT: "5432"
      DB_HOST: "db"
      DB_USER: "postgres"
      DB_NAME: "mydb"
      DB_PASSWORD: "mypassword"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      AWS_DEFAULT_REGION: "us-east-1"
    ports:
      - "4002:4002"
      - "50052:50052"
    volumes:
      - ./packages/service-blog:/app/packages/service-blog
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002/playground"]
      interval: 5s
      timeout: 3s
      retries: 5

  service-user:
    container_name: service-user
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./packages/service-user/Dockerfile.dev
    networks:
      - mycontent-network
    environment:
      GRAPHQL_PORT: "4003"
      USER_GRPC_PORT: "50053"
      DB_PORT: "5432"
      DB_HOST: "db"
      DB_USER: "postgres"
      DB_NAME: "mydb"
      DB_PASSWORD: "mypassword"
    ports:
      - "4003:4003"
      - "50053:50053"
    volumes:
      - ./packages/service-user:/app/packages/service-user
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4003/playground"]
      interval: 5s
      timeout: 3s
      retries: 5

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./packages/gateway/Dockerfile.dev
    environment:
      AUTHENTICATION_SERVICE_HOST: "http://service-authentication"
      USER_SERVICE_HOST: "http://service-user"
      BLOG_SERVICE_HOST: "http://service-blog"
    depends_on:
      service-authentication:
        condition: service_healthy
      service-user:
        condition: service_healthy
      service-blog:
        condition: service_healthy
    networks:
      - mycontent-network
    ports:
      - "4000:4000"
    volumes:
      - ./packages/gateway/src:/app/src

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      DEBUG: ${DEBUG:-0}
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      AWS_DEFAULT_REGION: "us-east-1"
    networks:
      - mycontent-network

networks:
  mycontent-network:
    driver: bridge
