services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - mycontent-network

  service-user:
    container_name: service-user
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./packages/service-user/Dockerfile
    networks:
      - mycontent-network
    ports:
      - "4001:4001"

  service-content:
    container_name: service-content
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./packages/service-content/Dockerfile
    networks:
      - mycontent-network
    ports:
      - "4002:4002"

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./packages/gateway/Dockerfile
    depends_on:
      - service-user
      - service-content
    networks:
      - mycontent-network
    ports:
      - "4000:4000"

networks:
  mycontent-network:
