package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"time"

	"github.com/kokiebisu/mycontent/packages/service-authentication/graphql/generated"
	"github.com/kokiebisu/mycontent/packages/service-authentication/graphql/model"
)

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	user, err := r.UserServiceClient.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	
	return &model.User{
		ID: user.ID.String(),
		FirstName: user.FirstName,
		LastName: user.LastName,
		Email: user.Email,
		Username: user.Username,
		Interest: model.Interest(user.Interest),
		YearsOfExperience: int(user.YearsOfExperience),
		PublishTime: user.PublishTime.Format(time.RFC3339),
	}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
