package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"time"

	"github.com/kokiebisu/mycontent/packages/service-user/graphql/generated"
	"github.com/kokiebisu/mycontent/packages/service-user/graphql/model"
	"github.com/kokiebisu/mycontent/packages/shared/ent"
)

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input *model.UpdateUserInput) (*ent.User, error) {
	user, err := r.UserService.Update(ctx, id, input.FirstName, input.LastName, input.Email, input.Password, input.Interest, input.YearsOfExperience, input.Username)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*ent.User, error) {
	userID := ctx.Value("userID").(string)
	user, err := r.UserService.Get(ctx, userID)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*ent.User, error) {
	user, err := r.UserService.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*ent.User, error) {
	users, err := r.UserService.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	return users, nil
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *ent.User) (string, error) {
	return obj.ID.String(), nil
}

// PublishTime is the resolver for the publishTime field.
func (r *userResolver) PublishTime(ctx context.Context, obj *ent.User) (string, error) {
	return obj.PublishTime.Format(time.RFC3339), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *ent.User) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *ent.User) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
