// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	FirstName         string   `json:"firstName"`
	LastName          string   `json:"lastName"`
	Email             string   `json:"email"`
	Username          string   `json:"username"`
	Password          string   `json:"password"`
	Interests         []string `json:"interests"`
	YearsOfExperience int      `json:"yearsOfExperience"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserInput struct {
	FirstName         string   `json:"firstName"`
	LastName          string   `json:"lastName"`
	Email             string   `json:"email"`
	Username          string   `json:"username"`
	Password          string   `json:"password"`
	Interests         []string `json:"interests"`
	YearsOfExperience int      `json:"yearsOfExperience"`
}

type User struct {
	ID                string   `json:"id"`
	FirstName         string   `json:"firstName"`
	LastName          string   `json:"lastName"`
	Email             string   `json:"email"`
	Username          string   `json:"username"`
	Password          string   `json:"password"`
	Interests         []string `json:"interests"`
	YearsOfExperience int      `json:"yearsOfExperience"`
	CreatedAt         string   `json:"createdAt"`
	UpdatedAt         string   `json:"updatedAt"`
}

func (User) IsEntity() {}
