// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Content struct {
	ID          string `json:"id"`
	ContentType string `json:"content_type"`
	Title       string `json:"title"`
	Creator     string `json:"creator"`
	ImageURL    string `json:"image_url"`
	UpdatedAt   string `json:"updated_at"`
}

func (Content) IsEntity() {}

type CreateContentInput struct {
	ContentType string `json:"content_type"`
	Title       string `json:"title"`
	Creator     string `json:"creator"`
	ImageURL    string `json:"image_url"`
}

type Mutation struct {
}

type Query struct {
}
