// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Blog is the predicate function for blog builders.
type Blog func(*sql.Selector)

// Integration is the predicate function for integration builders.
type Integration func(*sql.Selector)
