// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CreateUserInput struct {
	Name            string `json:"name"`
	Email           string `json:"email"`
	PersonalityType string `json:"personality_type"`
	Username        string `json:"username"`
	Password        string `json:"password"`
}
