// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kokiebisu/mycontent/packages/shared/ent/integration"
	"github.com/kokiebisu/mycontent/packages/shared/ent/predicate"
)

// IntegrationUpdate is the builder for updating Integration entities.
type IntegrationUpdate struct {
	config
	hooks    []Hook
	mutation *IntegrationMutation
}

// Where appends a list predicates to the IntegrationUpdate builder.
func (iu *IntegrationUpdate) Where(ps ...predicate.Integration) *IntegrationUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetPlatform sets the "platform" field.
func (iu *IntegrationUpdate) SetPlatform(i integration.Platform) *IntegrationUpdate {
	iu.mutation.SetPlatform(i)
	return iu
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (iu *IntegrationUpdate) SetNillablePlatform(i *integration.Platform) *IntegrationUpdate {
	if i != nil {
		iu.SetPlatform(*i)
	}
	return iu
}

// SetAPIKey sets the "api_key" field.
func (iu *IntegrationUpdate) SetAPIKey(s string) *IntegrationUpdate {
	iu.mutation.SetAPIKey(s)
	return iu
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (iu *IntegrationUpdate) SetNillableAPIKey(s *string) *IntegrationUpdate {
	if s != nil {
		iu.SetAPIKey(*s)
	}
	return iu
}

// ClearAPIKey clears the value of the "api_key" field.
func (iu *IntegrationUpdate) ClearAPIKey() *IntegrationUpdate {
	iu.mutation.ClearAPIKey()
	return iu
}

// SetUserID sets the "user_id" field.
func (iu *IntegrationUpdate) SetUserID(u uuid.UUID) *IntegrationUpdate {
	iu.mutation.SetUserID(u)
	return iu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (iu *IntegrationUpdate) SetNillableUserID(u *uuid.UUID) *IntegrationUpdate {
	if u != nil {
		iu.SetUserID(*u)
	}
	return iu
}

// SetCreatedAt sets the "created_at" field.
func (iu *IntegrationUpdate) SetCreatedAt(t time.Time) *IntegrationUpdate {
	iu.mutation.SetCreatedAt(t)
	return iu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iu *IntegrationUpdate) SetNillableCreatedAt(t *time.Time) *IntegrationUpdate {
	if t != nil {
		iu.SetCreatedAt(*t)
	}
	return iu
}

// SetUpdatedAt sets the "updated_at" field.
func (iu *IntegrationUpdate) SetUpdatedAt(t time.Time) *IntegrationUpdate {
	iu.mutation.SetUpdatedAt(t)
	return iu
}

// Mutation returns the IntegrationMutation object of the builder.
func (iu *IntegrationUpdate) Mutation() *IntegrationMutation {
	return iu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *IntegrationUpdate) Save(ctx context.Context) (int, error) {
	iu.defaults()
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *IntegrationUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *IntegrationUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *IntegrationUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iu *IntegrationUpdate) defaults() {
	if _, ok := iu.mutation.UpdatedAt(); !ok {
		v := integration.UpdateDefaultUpdatedAt()
		iu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iu *IntegrationUpdate) check() error {
	if v, ok := iu.mutation.Platform(); ok {
		if err := integration.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Integration.platform": %w`, err)}
		}
	}
	if v, ok := iu.mutation.APIKey(); ok {
		if err := integration.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "Integration.api_key": %w`, err)}
		}
	}
	return nil
}

func (iu *IntegrationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := iu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(integration.Table, integration.Columns, sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.Platform(); ok {
		_spec.SetField(integration.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := iu.mutation.APIKey(); ok {
		_spec.SetField(integration.FieldAPIKey, field.TypeString, value)
	}
	if iu.mutation.APIKeyCleared() {
		_spec.ClearField(integration.FieldAPIKey, field.TypeString)
	}
	if value, ok := iu.mutation.UserID(); ok {
		_spec.SetField(integration.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := iu.mutation.CreatedAt(); ok {
		_spec.SetField(integration.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := iu.mutation.UpdatedAt(); ok {
		_spec.SetField(integration.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{integration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// IntegrationUpdateOne is the builder for updating a single Integration entity.
type IntegrationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IntegrationMutation
}

// SetPlatform sets the "platform" field.
func (iuo *IntegrationUpdateOne) SetPlatform(i integration.Platform) *IntegrationUpdateOne {
	iuo.mutation.SetPlatform(i)
	return iuo
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (iuo *IntegrationUpdateOne) SetNillablePlatform(i *integration.Platform) *IntegrationUpdateOne {
	if i != nil {
		iuo.SetPlatform(*i)
	}
	return iuo
}

// SetAPIKey sets the "api_key" field.
func (iuo *IntegrationUpdateOne) SetAPIKey(s string) *IntegrationUpdateOne {
	iuo.mutation.SetAPIKey(s)
	return iuo
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (iuo *IntegrationUpdateOne) SetNillableAPIKey(s *string) *IntegrationUpdateOne {
	if s != nil {
		iuo.SetAPIKey(*s)
	}
	return iuo
}

// ClearAPIKey clears the value of the "api_key" field.
func (iuo *IntegrationUpdateOne) ClearAPIKey() *IntegrationUpdateOne {
	iuo.mutation.ClearAPIKey()
	return iuo
}

// SetUserID sets the "user_id" field.
func (iuo *IntegrationUpdateOne) SetUserID(u uuid.UUID) *IntegrationUpdateOne {
	iuo.mutation.SetUserID(u)
	return iuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (iuo *IntegrationUpdateOne) SetNillableUserID(u *uuid.UUID) *IntegrationUpdateOne {
	if u != nil {
		iuo.SetUserID(*u)
	}
	return iuo
}

// SetCreatedAt sets the "created_at" field.
func (iuo *IntegrationUpdateOne) SetCreatedAt(t time.Time) *IntegrationUpdateOne {
	iuo.mutation.SetCreatedAt(t)
	return iuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iuo *IntegrationUpdateOne) SetNillableCreatedAt(t *time.Time) *IntegrationUpdateOne {
	if t != nil {
		iuo.SetCreatedAt(*t)
	}
	return iuo
}

// SetUpdatedAt sets the "updated_at" field.
func (iuo *IntegrationUpdateOne) SetUpdatedAt(t time.Time) *IntegrationUpdateOne {
	iuo.mutation.SetUpdatedAt(t)
	return iuo
}

// Mutation returns the IntegrationMutation object of the builder.
func (iuo *IntegrationUpdateOne) Mutation() *IntegrationMutation {
	return iuo.mutation
}

// Where appends a list predicates to the IntegrationUpdate builder.
func (iuo *IntegrationUpdateOne) Where(ps ...predicate.Integration) *IntegrationUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *IntegrationUpdateOne) Select(field string, fields ...string) *IntegrationUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Integration entity.
func (iuo *IntegrationUpdateOne) Save(ctx context.Context) (*Integration, error) {
	iuo.defaults()
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *IntegrationUpdateOne) SaveX(ctx context.Context) *Integration {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *IntegrationUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *IntegrationUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iuo *IntegrationUpdateOne) defaults() {
	if _, ok := iuo.mutation.UpdatedAt(); !ok {
		v := integration.UpdateDefaultUpdatedAt()
		iuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iuo *IntegrationUpdateOne) check() error {
	if v, ok := iuo.mutation.Platform(); ok {
		if err := integration.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Integration.platform": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.APIKey(); ok {
		if err := integration.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "Integration.api_key": %w`, err)}
		}
	}
	return nil
}

func (iuo *IntegrationUpdateOne) sqlSave(ctx context.Context) (_node *Integration, err error) {
	if err := iuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(integration.Table, integration.Columns, sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Integration.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, integration.FieldID)
		for _, f := range fields {
			if !integration.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != integration.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.Platform(); ok {
		_spec.SetField(integration.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := iuo.mutation.APIKey(); ok {
		_spec.SetField(integration.FieldAPIKey, field.TypeString, value)
	}
	if iuo.mutation.APIKeyCleared() {
		_spec.ClearField(integration.FieldAPIKey, field.TypeString)
	}
	if value, ok := iuo.mutation.UserID(); ok {
		_spec.SetField(integration.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := iuo.mutation.CreatedAt(); ok {
		_spec.SetField(integration.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := iuo.mutation.UpdatedAt(); ok {
		_spec.SetField(integration.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Integration{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{integration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
