// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kokiebisu/mycontent/packages/shared/ent/integration"
)

// IntegrationCreate is the builder for creating a Integration entity.
type IntegrationCreate struct {
	config
	mutation *IntegrationMutation
	hooks    []Hook
}

// SetPlatform sets the "platform" field.
func (ic *IntegrationCreate) SetPlatform(i integration.Platform) *IntegrationCreate {
	ic.mutation.SetPlatform(i)
	return ic
}

// SetAPIKey sets the "api_key" field.
func (ic *IntegrationCreate) SetAPIKey(s string) *IntegrationCreate {
	ic.mutation.SetAPIKey(s)
	return ic
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (ic *IntegrationCreate) SetNillableAPIKey(s *string) *IntegrationCreate {
	if s != nil {
		ic.SetAPIKey(*s)
	}
	return ic
}

// SetUserID sets the "user_id" field.
func (ic *IntegrationCreate) SetUserID(u uuid.UUID) *IntegrationCreate {
	ic.mutation.SetUserID(u)
	return ic
}

// SetCreatedAt sets the "created_at" field.
func (ic *IntegrationCreate) SetCreatedAt(t time.Time) *IntegrationCreate {
	ic.mutation.SetCreatedAt(t)
	return ic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ic *IntegrationCreate) SetNillableCreatedAt(t *time.Time) *IntegrationCreate {
	if t != nil {
		ic.SetCreatedAt(*t)
	}
	return ic
}

// SetUpdatedAt sets the "updated_at" field.
func (ic *IntegrationCreate) SetUpdatedAt(t time.Time) *IntegrationCreate {
	ic.mutation.SetUpdatedAt(t)
	return ic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ic *IntegrationCreate) SetNillableUpdatedAt(t *time.Time) *IntegrationCreate {
	if t != nil {
		ic.SetUpdatedAt(*t)
	}
	return ic
}

// SetID sets the "id" field.
func (ic *IntegrationCreate) SetID(u uuid.UUID) *IntegrationCreate {
	ic.mutation.SetID(u)
	return ic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ic *IntegrationCreate) SetNillableID(u *uuid.UUID) *IntegrationCreate {
	if u != nil {
		ic.SetID(*u)
	}
	return ic
}

// Mutation returns the IntegrationMutation object of the builder.
func (ic *IntegrationCreate) Mutation() *IntegrationMutation {
	return ic.mutation
}

// Save creates the Integration in the database.
func (ic *IntegrationCreate) Save(ctx context.Context) (*Integration, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *IntegrationCreate) SaveX(ctx context.Context) *Integration {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *IntegrationCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *IntegrationCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *IntegrationCreate) defaults() {
	if _, ok := ic.mutation.CreatedAt(); !ok {
		v := integration.DefaultCreatedAt()
		ic.mutation.SetCreatedAt(v)
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		v := integration.DefaultUpdatedAt()
		ic.mutation.SetUpdatedAt(v)
	}
	if _, ok := ic.mutation.ID(); !ok {
		v := integration.DefaultID()
		ic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *IntegrationCreate) check() error {
	if _, ok := ic.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Integration.platform"`)}
	}
	if v, ok := ic.mutation.Platform(); ok {
		if err := integration.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Integration.platform": %w`, err)}
		}
	}
	if v, ok := ic.mutation.APIKey(); ok {
		if err := integration.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "Integration.api_key": %w`, err)}
		}
	}
	if _, ok := ic.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Integration.user_id"`)}
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Integration.created_at"`)}
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Integration.updated_at"`)}
	}
	return nil
}

func (ic *IntegrationCreate) sqlSave(ctx context.Context) (*Integration, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *IntegrationCreate) createSpec() (*Integration, *sqlgraph.CreateSpec) {
	var (
		_node = &Integration{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(integration.Table, sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID))
	)
	if id, ok := ic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ic.mutation.Platform(); ok {
		_spec.SetField(integration.FieldPlatform, field.TypeEnum, value)
		_node.Platform = value
	}
	if value, ok := ic.mutation.APIKey(); ok {
		_spec.SetField(integration.FieldAPIKey, field.TypeString, value)
		_node.APIKey = value
	}
	if value, ok := ic.mutation.UserID(); ok {
		_spec.SetField(integration.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := ic.mutation.CreatedAt(); ok {
		_spec.SetField(integration.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ic.mutation.UpdatedAt(); ok {
		_spec.SetField(integration.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// IntegrationCreateBulk is the builder for creating many Integration entities in bulk.
type IntegrationCreateBulk struct {
	config
	err      error
	builders []*IntegrationCreate
}

// Save creates the Integration entities in the database.
func (icb *IntegrationCreateBulk) Save(ctx context.Context) ([]*Integration, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Integration, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IntegrationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *IntegrationCreateBulk) SaveX(ctx context.Context) []*Integration {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *IntegrationCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *IntegrationCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
