package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"fmt"
)

// FindBlogByID is the resolver for the findBlogByID field.
func (r *entityResolver) FindBlogByID(ctx context.Context, id string) (*Blog, error) {
	panic(fmt.Errorf("not implemented: FindBlogByID - findBlogByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
