// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Blog struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

func (Blog) IsEntity() {}

type Mutation struct {
}

type Query struct {
}
