version: "3"

tasks:
  generate:graphql:
    cmds:
      - gqlgen generate

  generate:stub:
    cmds:
      - protoc --go_out=./stub --go_opt=paths=source_relative --go-grpc_out=./stub --go-grpc_opt=paths=source_relative -I ../shared/proto ../shared/proto/blog.proto
