# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nblog.proto\"T\n\x11\x43reateBlogRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\"/\n\x12\x43reateBlogResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2D\n\x0b\x42logService\x12\x35\n\nCreateBlog\x12\x12.CreateBlogRequest\x1a\x13.CreateBlogResponseB<Z:github.com/kokiebisu/mycontent/packages/service-blog/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/kokiebisu/mycontent/packages/service-blog/proto'
  _globals['_CREATEBLOGREQUEST']._serialized_start=14
  _globals['_CREATEBLOGREQUEST']._serialized_end=98
  _globals['_CREATEBLOGRESPONSE']._serialized_start=100
  _globals['_CREATEBLOGRESPONSE']._serialized_end=147
  _globals['_BLOGSERVICE']._serialized_start=149
  _globals['_BLOGSERVICE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
