// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/kokiebisu/mycontent/packages/service-content/ent/content"
	"github.com/kokiebisu/mycontent/packages/service-content/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contentFields := schema.Content{}.Fields()
	_ = contentFields
	// contentDescUpdatedAt is the schema descriptor for updated_at field.
	contentDescUpdatedAt := contentFields[4].Descriptor()
	// content.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	content.DefaultUpdatedAt = contentDescUpdatedAt.Default.(func() time.Time)
	// content.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	content.UpdateDefaultUpdatedAt = contentDescUpdatedAt.UpdateDefault.(func() time.Time)
}
